import { User, Verse, TextWork, Proposal, Comment, ActivityEntry, Merkinta, Snapshot } from './types'

// Filippiläiskirje — parsed from RK26-03/50 Fil.docx
// Base text = first occurrence, proposal text = second occurrence (where present)
export const SEED_VERSES: Verse[] = [
  {
    chapter: 1,
    number: 1,
    baseText: 'Paavali ja Timoteus, Kristuksen Jeesuksen palvelijat, kaikille Filippissä oleville pyhille Kristuksessa Jeesuksessa sekä seurakunnan kaitsijoille ja seurakuntapalvelijoille.',
    approvedText: 'Paavali ja Timoteus, Kristuksen Jeesuksen palvelijat, kaikille Filippissä oleville pyhille Kristuksessa Jeesuksessa sekä seurakunnan kaitsijoille ja seurakuntapalvelijoille.',
    text: 'Paavali ja Timoteus, Kristuksen Jeesuksen palvelijat, kaikille Filippissä oleville pyhille Kristuksessa Jeesuksessa sekä seurakunnan kaitsijoille ja seurakuntapalvelijoille.',
    sectionHeader: 'Alkutervehdys',
  },
  {
    chapter: 1,
    number: 2,
    baseText: 'Armo teille ja rauha Jumalalta, meidän Isältämme, ja Herralta Jeesukselta Kristukselta!',
    approvedText: 'Armo teille ja rauha Jumalalta, meidän Isältämme, ja Herralta Jeesukselta Kristukselta!',
    text: 'Armo teille ja rauha Jumalalta, meidän Isältämme, ja Herralta Jeesukselta Kristukselta!',
  },
  {
    chapter: 1,
    number: 3,
    baseText: 'Minä kiitän Jumalaani niin usein kuin muistan teitä.',
    approvedText: 'Minä kiitän Jumalaani niin usein kuin muistan teitä.',
    text: 'Minä kiitän Jumalaani niin usein kuin muistan teitä.',
    sectionHeader: 'Rukous kirjeen lukijoiden puolesta',
  },
  {
    chapter: 1,
    number: 4,
    baseText: 'Kaikissa rukouksissani rukoilen aina iloiten teidän kaikkien puolesta.',
    approvedText: 'Kaikissa rukouksissani rukoilen aina iloiten teidän kaikkien puolesta.',
    text: 'Kaikissa rukouksissani rukoilen aina iloiten teidän kaikkien puolesta.',
  },
  {
    chapter: 1,
    number: 5,
    baseText: 'Kiitän siitä, että olette osallistuneet evankeliumin työhön* ensi päivästä tähän asti,',
    approvedText: 'Kiitän siitä, että olette osallistuneet evankeliumin työhön* ensi päivästä tähän asti,',
    text: 'Kiitän siitä, että olette osallistuneet evankeliumin työhön* ensi päivästä tähän asti,',
    footnotes: [{ marker: '1:5', text: '1:5 Tai ”olette olleet osalliset evankeliumiin”.', baseText: '1:5 Tai ”olette olleet osalliset evankeliumiin”.' }],
  },
  {
    chapter: 1,
    number: 6,
    baseText: 'ja luotan täysin siihen, että hän, joka on alkanut teissä hyvän työn, vie sen päätökseen Kristuksen Jeesuksen päivään mennessä.',
    approvedText: 'ja luotan täysin siihen, että hän, joka on alkanut teissä hyvän työn, vie sen päätökseen Kristuksen Jeesuksen päivään mennessä.',
    text: 'ja luotan täysin siihen, että hän, joka on alkanut teissä hyvän työn, vie sen päätökseen Kristuksen Jeesuksen päivään mennessä.',
  },
  {
    chapter: 1,
    number: 7,
    baseText: 'Onkin oikein, että ajattelen näin teistä kaikista, koska te olette minun sydämessäni. Niin kahleissa ollessani kuin puolustaessani ja vahvistaessani evankeliumia te kaikki olette minun kanssani osallisia armosta.',
    approvedText: 'Onkin oikein, että ajattelen näin teistä kaikista, koska te olette minun sydämessäni. Niin kahleissa ollessani kuin puolustaessani ja vahvistaessani evankeliumia te kaikki olette minun kanssani osallisia armosta.',
    text: 'Onkin oikein, että ajattelen näin teistä kaikista, koska te olette minun sydämessäni, ja olenpa sitten kahleissa tai puolustamassa ja vahvistamassa evankeliumia, te kaikki olette minun kanssani osallisia armosta.',
  },
  {
    chapter: 1,
    number: 8,
    baseText: 'Jumala on todistajani, kuinka minä kaipaan teitä kaikkia Kristuksen Jeesuksen sydämellisellä rakkaudella.',
    approvedText: 'Jumala on todistajani, kuinka minä kaipaan teitä kaikkia Kristuksen Jeesuksen sydämellisellä rakkaudella.',
    text: 'Jumala on todistajani, kuinka minä kaipaan teitä kaikkia Kristuksen Jeesuksen sydämellisellä rakkaudella.',
  },
  {
    chapter: 1,
    number: 9,
    baseText: 'Rukoilen myös, että teidän rakkautenne kasvaisi ja tieto ja kaikenlainen ymmärrys lisääntyisi,',
    approvedText: 'Rukoilen myös, että teidän rakkautenne kasvaisi ja tieto ja kaikenlainen ymmärrys lisääntyisi,',
    text: 'Rukoilen myös, että teidän rakkautenne kasvaisi ja tieto ja kaikenlainen ymmärrys lisääntyisi,',
  },
  {
    chapter: 1,
    number: 10,
    baseText: 'niin että voisitte tutkia, mikä on parasta, ja olisitte puhtaita ja moitteettomia Kristuksen päivään saakka,',
    approvedText: 'niin että voisitte tutkia, mikä on parasta, ja olisitte puhtaita ja moitteettomia Kristuksen päivään saakka,',
    text: 'niin että voisitte tutkia, mikä on parasta, ja olisitte puhtaita ja moitteettomia Kristuksen päivään saakka,',
  },
  {
    chapter: 1,
    number: 11,
    baseText: 'täynnä vanhurskauden hedelmää, jonka Jeesus Kristus saa aikaan Jumalan kunniaksi ja ylistykseksi.',
    approvedText: 'täynnä vanhurskauden hedelmää, jonka Jeesus Kristus saa aikaan Jumalan kunniaksi ja ylistykseksi.',
    text: 'täynnä vanhurskauden hedelmää, jonka Jeesus Kristus saa aikaan Jumalan kunniaksi ja ylistykseksi.',
  },
  {
    chapter: 1,
    number: 12,
    baseText: 'Tahdon teidän tietävän, veljet, että se, mitä minulle on tapahtunut, onkin koitunut evankeliumin menestykseksi.',
    approvedText: 'Tahdon teidän tietävän, veljet, että se, mitä minulle on tapahtunut, onkin koitunut evankeliumin menestykseksi.',
    text: 'Tahdon teidän tietävän, veljet, että se, mitä minulle on tapahtunut, onkin koitunut evankeliumin menestykseksi.',
    sectionHeader: 'Elämä on minulle Kristus',
  },
  {
    chapter: 1,
    number: 13,
    baseText: 'Niinpä koko henkivartioston ja kaikkien muidenkin tietoon on tullut, että minä olen kahleissa Kristuksen tähden.',
    approvedText: 'Niinpä koko henkivartioston ja kaikkien muidenkin tietoon on tullut, että minä olen kahleissa Kristuksen tähden.',
    text: 'Niinpä koko henkivartioston ja kaikkien muidenkin tietoon on tullut, että minä olen kahleissa Kristuksen tähden.',
  },
  {
    chapter: 1,
    number: 14,
    baseText: 'Useimmat veljistä ovat saaneet kahleistani rohkeutta Herrassa ja uskaltavat yhä enemmän puhua Jumalan sanaa ilman pelkoa.',
    approvedText: 'Useimmat veljistä ovat saaneet kahleistani rohkeutta Herrassa ja uskaltavat yhä enemmän puhua Jumalan sanaa ilman pelkoa.',
    text: 'Useimmat veljistä ovat saaneet kahleistani rohkeutta Herrassa ja uskaltavat yhä enemmän puhua Jumalan sanaa ilman pelkoa.',
  },
  {
    chapter: 1,
    number: 15,
    baseText: 'Jotkut tosin julistavat Kristusta kateudesta ja riidanhalusta mutta toiset hyvässä tarkoituksessa.',
    approvedText: 'Jotkut tosin julistavat Kristusta kateudesta ja riidanhalusta mutta toiset hyvässä tarkoituksessa.',
    text: 'Jotkut tosin julistavat Kristusta kateudesta ja riidanhalusta mutta toiset hyvässä tarkoituksessa.',
  },
  {
    chapter: 1,
    number: 16,
    baseText: 'He tekevät sen rakkaudesta, koska tietävät, että minut on pantu puolustamaan evankeliumia.',
    approvedText: 'He tekevät sen rakkaudesta, koska tietävät, että minut on pantu puolustamaan evankeliumia.',
    text: 'Toiset tekevät sitä rakkaudesta, koska he tietävät, että minut on pantu puolustamaan evankeliumia,',
  },
  {
    chapter: 1,
    number: 17,
    baseText: 'Nuo toiset taas julistavat Kristusta itsekkyydestä, epäpuhtain mielin, ja luulevat tuottavansa minulle murhetta kahleissani.',
    approvedText: 'Nuo toiset taas julistavat Kristusta itsekkyydestä, epäpuhtain mielin, ja luulevat tuottavansa minulle murhetta kahleissani.',
    text: 'ja nuo toiset taas julistavat Kristusta itsekkyydestä, epäpuhtain mielin, ja luulevat tuottavansa minulle murhetta kahleissani.',
  },
  {
    chapter: 1,
    number: 18,
    baseText: 'Mitäpä tuosta, kunhan vain Kristusta tavalla tai toisella julistetaan, joko näön vuoksi tai totuudessa, ja siitä minä iloitsen. Vastedeskin saan iloita,',
    approvedText: 'Mitäpä tuosta, kunhan vain Kristusta tavalla tai toisella julistetaan, joko näön vuoksi tai totuudessa, ja siitä minä iloitsen. Vastedeskin saan iloita,',
    text: 'Mitäpä tuosta, kunhan vain Kristusta tavalla tai toisella julistetaan, joko näön vuoksi tai totuudessa. Siitä minä iloitsen nyt ja vastedeskin,',
  },
  {
    chapter: 1,
    number: 19,
    baseText: 'sillä minä tiedän, että teidän rukoustenne kautta ja Jeesuksen Kristuksen Hengen avulla tämä kaikki koituu minulle pelastukseksi.',
    approvedText: 'sillä minä tiedän, että teidän rukoustenne kautta ja Jeesuksen Kristuksen Hengen avulla tämä kaikki koituu minulle pelastukseksi.',
    text: 'sillä minä tiedän, että teidän rukoustenne kautta ja Jeesuksen Kristuksen Hengen avulla tämä kaikki koituu minulle pelastukseksi.',
  },
  {
    chapter: 1,
    number: 20,
    baseText: 'Harras odotukseni ja toivoni on, etten joudu millään tavoin häpeään vaan että Kristus nyt, niin kuin aina, tulee rohkeasti ylistetyksi minun ruumiissani, joko elämän tai kuoleman kautta.',
    approvedText: 'Harras odotukseni ja toivoni on, etten joudu millään tavoin häpeään vaan että Kristus nyt, niin kuin aina, tulee rohkeasti ylistetyksi minun ruumiissani, joko elämän tai kuoleman kautta.',
    text: 'Harras odotukseni ja toivoni on, etten joudu millään tavoin häpeään vaan että Kristus nyt, niin kuin aina, tulee rohkeasti ylistetyksi minun ruumiissani, joko elämän tai kuoleman kautta.',
  },
  {
    chapter: 1,
    number: 21,
    baseText: 'Sillä minulle elämä on Kristus ja kuolema on voitto.',
    approvedText: 'Sillä minulle elämä on Kristus ja kuolema on voitto.',
    text: 'Sillä minulle elämä on Kristus ja kuolema on voitto.',
  },
  {
    chapter: 1,
    number: 22,
    baseText: 'Jos minun on elettävä lihassa, se tuottaa hedelmää työlleni. En tiedä, kumman valitsisin.',
    approvedText: 'Jos minun on elettävä lihassa, se tuottaa hedelmää työlleni. En tiedä, kumman valitsisin.',
    text: 'Jos minun on elettävä lihassa, se tuottaa hedelmää työlleni. En tiedä, kumman valitsisin.',
  },
  {
    chapter: 1,
    number: 23,
    baseText: 'Olen ahtaalla näiden kahden välissä. Haluaisin lähteä täältä ja olla Kristuksen kanssa, sillä se olisi verrattomasti parempi,',
    approvedText: 'Olen ahtaalla näiden kahden välissä. Haluaisin lähteä täältä ja olla Kristuksen kanssa, sillä se olisi verrattomasti parempi,',
    text: 'Olen ahtaalla näiden kahden välissä. Haluaisin lähteä täältä ja olla Kristuksen kanssa, sillä se olisi verrattomasti parempi,',
  },
  {
    chapter: 1,
    number: 24,
    baseText: 'mutta teidän vuoksenne on lihassa viipymiseni tarpeellisempi.',
    approvedText: 'mutta teidän vuoksenne on lihassa viipymiseni tarpeellisempi.',
    text: 'mutta teidän vuoksenne on lihassa viipymiseni tarpeellisempi.',
  },
  {
    chapter: 1,
    number: 25,
    baseText: 'Koska olen tästä varma, tiedän, että jään eloon ja pysyn kaikkien teidän luonanne, jotta edistyisitte uskossa ja saisitte siitä iloita.',
    approvedText: 'Koska olen tästä varma, tiedän, että jään eloon ja pysyn kaikkien teidän luonanne, jotta edistyisitte uskossa ja saisitte siitä iloita.',
    text: 'Koska olen tästä varma, tiedän, että jään eloon ja pysyn kaikkien teidän luonanne, jotta edistyisitte uskossa ja saisitte siitä iloita.',
  },
  {
    chapter: 1,
    number: 26,
    baseText: 'Näin teidän kerskaamisenne minusta olisi yhä runsaampaa Kristuksessa Jeesuksessa, kun taas tulen luoksenne.',
    approvedText: 'Näin teidän kerskaamisenne minusta olisi yhä runsaampaa Kristuksessa Jeesuksessa, kun taas tulen luoksenne.',
    text: 'Silloin voitte iloita minusta ja ylistää Kristusta Jeesusta yhä enemmän, kun taas tulen luoksenne.',
  },
  {
    chapter: 1,
    number: 27,
    baseText: 'Käyttäytykää vain Kristuksen evankeliumin arvon mukaisesti. Silloin minä, tulenpa luoksenne ja näen teidät tai olen tulematta, saan kuulla teistä, että pysytte samassa hengessä ja yksimielisesti taistelette yhdessä evankeliumin uskon puolesta',
    approvedText: 'Käyttäytykää vain Kristuksen evankeliumin arvon mukaisesti. Silloin minä, tulenpa luoksenne ja näen teidät tai olen tulematta, saan kuulla teistä, että pysytte samassa hengessä ja yksimielisesti taistelette yhdessä evankeliumin uskon puolesta',
    text: 'Käyttäytykää vain niin kuin Kristuksen evankeliumin arvo vaatii. Silloin minä, tulenpa luoksenne ja näen teidät tai olen tulematta, saan kuulla teistä, että pysytte samassa hengessä ja yksimielisesti taistelette yhdessä evankeliumin uskon puolesta',
  },
  {
    chapter: 1,
    number: 28,
    baseText: 'antamatta vastustajien millään tavoin säikyttää itseänne. Tämä on heille kadotuksen mutta teille pelastuksen merkki, ja se tulee Jumalalta.',
    approvedText: 'antamatta vastustajien millään tavoin säikyttää itseänne. Tämä on heille kadotuksen mutta teille pelastuksen merkki, ja se tulee Jumalalta.',
    text: 'antamatta vastustajien millään tavoin säikyttää itseänne. Se on heille kadotuksen mutta teille pelastuksen merkki, merkki Jumalalta.',
  },
  {
    chapter: 1,
    number: 29,
    baseText: 'Kristuksen tähden teidän on suotu, ei ainoastaan uskoa häneen vaan myös kärsiä hänen tähtensä.',
    approvedText: 'Kristuksen tähden teidän on suotu, ei ainoastaan uskoa häneen vaan myös kärsiä hänen tähtensä.',
    text: 'Sillä Kristuksen tähden teidän on suotu, ei ainoastaan uskoa häneen vaan myös kärsiä hänen tähtensä.',
  },
  {
    chapter: 1,
    number: 30,
    baseText: 'Teillä on sama taistelu, jota olette nähneet minun käyvän ja jota nyt kuulette minun yhä jatkavan.',
    approvedText: 'Teillä on sama taistelu, jota olette nähneet minun käyvän ja jota nyt kuulette minun yhä jatkavan.',
    text: 'Teillä on sama taistelu, jota olette nähneet minun käyvän ja jota nyt kuulette minun yhä jatkavan.',
  },
  {
    chapter: 2,
    number: 1,
    baseText: 'Jos siis on jotakin kehotusta Kristuksessa, jos jotakin rakkauden lohdutusta ja Hengen yhteyttä, jos jotakin sydämellisyyttä ja laupeutta,',
    approvedText: 'Jos siis on jotakin kehotusta Kristuksessa, jos jotakin rakkauden lohdutusta ja Hengen yhteyttä, jos jotakin sydämellisyyttä ja laupeutta,',
    text: 'Jos siis on jotakin rohkaisua Kristuksessa, jos jotakin rakkaudellista lohdutusta ja Hengen yhteyttä, ja jos on sydämellisyyttä ja laupeutta,',
    sectionHeader: 'Kristuksen nöyryys ja korotus',
  },
  {
    chapter: 2,
    number: 2,
    baseText: 'tehkää minun iloni täydelliseksi, niin että olette samaa mieltä, että teillä on sama rakkaus ja olette sopuisat ja yksimieliset.',
    approvedText: 'tehkää minun iloni täydelliseksi, niin että olette samaa mieltä, että teillä on sama rakkaus ja olette sopuisat ja yksimieliset.',
    text: 'tehkää minun iloni täydelliseksi, niin että olette samaa mieltä, että teillä on sama rakkaus ja olette sopuisat ja yksimieliset.',
  },
  {
    chapter: 2,
    number: 3,
    baseText: 'Älkää tehkö mitään itsekkyydestä tai turhan kunnian vuoksi, vaan pitäkää nöyrästi toista parempana kuin itseänne.',
    approvedText: 'Älkää tehkö mitään itsekkyydestä tai turhan kunnian vuoksi, vaan pitäkää nöyrästi toista parempana kuin itseänne.',
    text: 'Älkää tehkö mitään itsekkyydestä tai turhan kunnian vuoksi, vaan pitäkää nöyrästi toista parempana kuin itseänne.',
  },
  {
    chapter: 2,
    number: 4,
    baseText: 'Älkää katsoko vain omaa parastanne vaan myös toisten.',
    approvedText: 'Älkää katsoko vain omaa parastanne vaan myös toisten.',
    text: 'Älkää katsoko vain omaa parastanne vaan myös toisten.',
  },
  {
    chapter: 2,
    number: 5,
    baseText: 'Olkoon teillä se mieli, joka myös Kristuksella Jeesuksella oli.',
    approvedText: 'Olkoon teillä se mieli, joka myös Kristuksella Jeesuksella oli.',
    text: 'Olkoon teillä se mieli, joka myös Kristuksella Jeesuksella oli.',
  },
  {
    chapter: 2,
    number: 6,
    baseText: 'Hänellä oli Jumalan muoto,\nmutta hän ei katsonut saaliikseen / pitänyt kiinni oikeudestaan olla Jumalan kaltainen',
    approvedText: 'Hänellä oli Jumalan muoto,\nmutta hän ei katsonut saaliikseen / pitänyt kiinni oikeudestaan olla Jumalan kaltainen',
    text: 'Hänellä oli Jumalan muoto,\nmutta hän ei katsonut saaliikseen / pitänyt kiinni oikeudestaan olla Jumalan kaltainen',
  },
  {
    chapter: 2,
    number: 7,
    baseText: 'vaan tyhjensi itsensä / luopui omastaan ja otti orjan muodon.\nHän tuli ihmisten kaltaiseksi,\nja hänet havaittiin olemukseltaan sellaiseksi kuin ihminen.',
    approvedText: 'vaan tyhjensi itsensä / luopui omastaan ja otti orjan muodon.\nHän tuli ihmisten kaltaiseksi,\nja hänet havaittiin olemukseltaan sellaiseksi kuin ihminen.',
    text: 'vaan tyhjensi itsensä / luopui omastaan ja otti orjan muodon.\nHän tuli ihmisten kaltaiseksi,\nja hänet havaittiin olemukseltaan sellaiseksi kuin ihminen.',
  },
  {
    chapter: 2,
    number: 8,
    baseText: 'Hän nöyryytti itsensä ja oli kuuliainen kuolemaan asti,\naina ristinkuolemaan asti.',
    approvedText: 'Hän nöyryytti itsensä ja oli kuuliainen kuolemaan asti,\naina ristinkuolemaan asti.',
    text: 'Hän nöyryytti itsensä ja oli kuuliainen kuolemaan asti,\naina ristinkuolemaan asti.',
  },
  {
    chapter: 2,
    number: 9,
    baseText: 'Sen tähden Jumala onkin korottanut hänet korkealle\nja antanut hänelle nimen,\nkaikkia muita nimiä korkeamman,',
    approvedText: 'Sen tähden Jumala onkin korottanut hänet korkealle\nja antanut hänelle nimen,\nkaikkia muita nimiä korkeamman,',
    text: 'Sen tähden Jumala onkin korottanut hänet korkealle\nja antanut hänelle nimen,\nkaikkia muita nimiä korkeamman,',
  },
  {
    chapter: 2,
    number: 10,
    baseText: 'niin että jokaisen polven on notkistuttava Jeesuksen nimeen,\nniin taivaassa kuin maan päällä ja maan alla,',
    approvedText: 'niin että jokaisen polven on notkistuttava Jeesuksen nimeen,\nniin taivaassa kuin maan päällä ja maan alla,',
    text: 'niin että jokaisen polven on notkistuttava Jeesuksen nimeen,\nniin taivaassa kuin maan päällä ja maan alla,',
  },
  {
    chapter: 2,
    number: 11,
    baseText: 'ja jokaisen kielen on tunnustettava Isän Jumalan kunniaksi,\nettä Jeesus Kristus on Herra.',
    approvedText: 'ja jokaisen kielen on tunnustettava Isän Jumalan kunniaksi,\nettä Jeesus Kristus on Herra.',
    text: 'ja jokaisen kielen on tunnustettava Isän Jumalan kunniaksi,\nettä Jeesus Kristus on Herra.',
  },
  {
    chapter: 2,
    number: 12,
    baseText: 'Siksi, rakkaani, niin kuin olette aina olleet kuuliaisia, ei vain minun läsnä ollessani vaan vielä enemmän nyt, kun olen poissa, ahkeroikaa peläten ja vavisten oman pelastuksenne hyväksi.',
    approvedText: 'Siksi, rakkaani, niin kuin olette aina olleet kuuliaisia, ei vain minun läsnä ollessani vaan vielä enemmän nyt, kun olen poissa, ahkeroikaa peläten ja vavisten oman pelastuksenne hyväksi.',
    text: 'Siksi, rakkaani, niin kuin olette aina olleet kuuliaisia, ei vain minun läsnä ollessani vaan vielä enemmän nyt, kun olen poissa, ahkeroikaa peläten ja vavisten oman pelastuksenne hyväksi.',
    sectionHeader: 'Kristityn vaellus',
  },
  {
    chapter: 2,
    number: 13,
    baseText: 'Jumala itse vaikuttaa teissä tahtomisen ja tekemisen, että hänen hyvä tahtonsa tapahtuisi.',
    approvedText: 'Jumala itse vaikuttaa teissä tahtomisen ja tekemisen, että hänen hyvä tahtonsa tapahtuisi.',
    text: 'Jumala itse vaikuttaa teissä tahtomisen ja tekemisen, että hänen hyvä tahtonsa tapahtuisi.',
  },
  {
    chapter: 2,
    number: 14,
    baseText: 'Tehkää kaikki nurisematta ja epäröimättä,',
    approvedText: 'Tehkää kaikki nurisematta ja epäröimättä,',
    text: 'Tehkää kaikki nurisematta ja epäröimättä,',
  },
  {
    chapter: 2,
    number: 15,
    baseText: 'että olisitte moitteettomia ja puhtaita, tahrattomia Jumalan lapsia kieron ja turmeltuneen sukupolven keskellä. Te loistatte siinä kuin tähdet maailmassa,',
    approvedText: 'että olisitte moitteettomia ja puhtaita, tahrattomia Jumalan lapsia kieron ja turmeltuneen sukupolven keskellä. Te loistatte siinä kuin tähdet maailmassa,',
    text: 'että olisitte moitteettomia ja puhtaita, tahrattomia Jumalan lapsia kieron ja turmeltuneen sukupolven keskellä. Te loistatte siinä kuin tähdet maailmassa,',
  },
  {
    chapter: 2,
    number: 16,
    baseText: 'kun pidätte kiinni elämän sanasta*, ja silloin minä voin Kristuksen päivänä kerskata siitä, etten ole turhaan juossut ja nähnyt vaivaa.',
    approvedText: 'kun pidätte kiinni elämän sanasta*, ja silloin minä voin Kristuksen päivänä kerskata siitä, etten ole turhaan juossut ja nähnyt vaivaa.',
    text: 'kun pidätte kiinni elämän sanasta*, ja silloin minä voin Kristuksen päivänä iloita siitä, etten ole turhaan juossut ja nähnyt vaivaa.',
    footnotes: [{ marker: '2:16', text: '2:16 Tai ”pidätte esillä elämän sanaa”.', baseText: '2:16 Tai ”pidätte esillä elämän sanaa”.' }, { marker: '2:16', text: '2:16 Tai ”pidätte esillä elämän sanaa”. (tarpeen?)', baseText: '2:16 Tai ”pidätte esillä elämän sanaa”. (tarpeen?)' }],
  },
  {
    chapter: 2,
    number: 17,
    baseText: 'Mutta jos minut uhrataankin, kun toimitan teidän uskonne uhripalvelusta, minä iloitsen, ja iloitsen kaikkien teidän kanssanne.',
    approvedText: 'Mutta jos minut uhrataankin, kun toimitan teidän uskonne uhripalvelusta, minä iloitsen, ja iloitsen kaikkien teidän kanssanne.',
    text: 'Mutta jos minut uhrataankin, kun toimitan teidän uskonne uhripalvelusta, minä iloitsen, ja iloitsen kaikkien teidän kanssanne.',
  },
  {
    chapter: 2,
    number: 18,
    baseText: 'Samoin iloitkaa tekin ja iloitkaa yhdessä minun kanssani!',
    approvedText: 'Samoin iloitkaa tekin ja iloitkaa yhdessä minun kanssani!',
    text: 'Samoin iloitkaa tekin ja iloitkaa yhdessä minun kanssani!',
  },
  {
    chapter: 2,
    number: 19,
    baseText: 'Toivon Herrassa Jeesuksessa voivani pian lähettää Timoteuksen teidän luoksenne, että tulisin itsekin rohkaistuksi saatuani tietää, mitä teille kuuluu.',
    approvedText: 'Toivon Herrassa Jeesuksessa voivani pian lähettää Timoteuksen teidän luoksenne, että tulisin itsekin rohkaistuksi saatuani tietää, mitä teille kuuluu.',
    text: 'Toivon Herrassa Jeesuksessa voivani pian lähettää Timoteuksen teidän luoksenne, että tulisin itsekin rohkaistuksi saatuani tietää, mitä teille kuuluu.',
    sectionHeader: 'Timoteus ja Epafroditos',
  },
  {
    chapter: 2,
    number: 20,
    baseText: 'Minulla ei ole ketään toista samanmielistä, joka vilpittömästi huolehtisi teidän parhaastanne,',
    approvedText: 'Minulla ei ole ketään toista samanmielistä, joka vilpittömästi huolehtisi teidän parhaastanne,',
    text: 'Minulla ei ole ketään toista samanmielistä, joka vilpittömästi huolehtisi teidän parhaastanne,',
  },
  {
    chapter: 2,
    number: 21,
    baseText: 'sillä kaikki etsivät omaansa eivätkä sitä, mikä on Jeesuksen Kristuksen.',
    approvedText: 'sillä kaikki etsivät omaansa eivätkä sitä, mikä on Jeesuksen Kristuksen.',
    text: 'sillä kaikki etsivät omaansa eivätkä sitä, mikä on Jeesuksen Kristuksen.',
  },
  {
    chapter: 2,
    number: 22,
    baseText: 'Mutta Timoteuksen koetellun mielen te tunnette: kuin poika isän rinnalla hän on tehnyt minun kanssani työtä evankeliumin hyväksi.',
    approvedText: 'Mutta Timoteuksen koetellun mielen te tunnette: kuin poika isän rinnalla hän on tehnyt minun kanssani työtä evankeliumin hyväksi.',
    text: 'Mutta Timoteuksen koetellun mielen te tunnette. Hän on tehnyt minun kanssani työtä evankeliumin hyväksi kuin poika isänsä rinnalla.',
  },
  {
    chapter: 2,
    number: 23,
    baseText: 'Toivon voivani lähettää hänet matkaan heti kun näen, miten minun käy.',
    approvedText: 'Toivon voivani lähettää hänet matkaan heti kun näen, miten minun käy.',
    text: 'Toivon voivani lähettää hänet matkaan heti kun näen, miten minun käy.',
  },
  {
    chapter: 2,
    number: 24,
    baseText: 'Olen varma Herrassa siitä, että itsekin pääsen pian tulemaan.',
    approvedText: 'Olen varma Herrassa siitä, että itsekin pääsen pian tulemaan.',
    text: 'Olen varma Herrassa siitä, että itsekin pääsen pian tulemaan.',
  },
  {
    chapter: 2,
    number: 25,
    baseText: 'Minusta on kuitenkin välttämätöntä lähettää luoksenne veljeni, työkumppanini ja taistelutoverini Epafroditos, teidän lähettinne, joka auttaa minua siinä, missä tarvitsen.',
    approvedText: 'Minusta on kuitenkin välttämätöntä lähettää luoksenne veljeni, työkumppanini ja taistelutoverini Epafroditos, teidän lähettinne, joka auttaa minua siinä, missä tarvitsen.',
    text: 'Minusta on kuitenkin välttämätöntä lähettää luoksenne veljeni, työkumppanini ja taistelutoverini Epafroditos, teidän lähettinne, joka auttaa minua siinä, missä tarvitsen.',
  },
  {
    chapter: 2,
    number: 26,
    baseText: 'Hän näet ikävöi teitä kaikkia ja oli kovin levoton, koska olitte kuulleet hänen sairastuneen.',
    approvedText: 'Hän näet ikävöi teitä kaikkia ja oli kovin levoton, koska olitte kuulleet hänen sairastuneen.',
    text: 'Hän näet ikävöi teitä kaikkia ja oli kovin levoton, koska olitte kuulleet hänen sairastuneen.',
  },
  {
    chapter: 2,
    number: 27,
    baseText: 'Hän olikin sairaana, kuoleman kielissä, mutta Jumala armahti häntä, eikä ainoastaan häntä vaan myös minua, etten saisi murhetta murheen lisäksi.',
    approvedText: 'Hän olikin sairaana, kuoleman kielissä, mutta Jumala armahti häntä, eikä ainoastaan häntä vaan myös minua, etten saisi murhetta murheen lisäksi.',
    text: 'Hän olikin sairaana, kuoleman kielissä, mutta Jumala armahti häntä, eikä ainoastaan häntä vaan myös minua, etten saisi murhetta murheen lisäksi.',
  },
  {
    chapter: 2,
    number: 28,
    baseText: 'Lähetän hänet sen vuoksi kiireesti, että iloitsisitte nähdessänne hänet jälleen ja minullakin olisi vähemmän murheita.',
    approvedText: 'Lähetän hänet sen vuoksi kiireesti, että iloitsisitte nähdessänne hänet jälleen ja minullakin olisi vähemmän murheita.',
    text: 'Lähetän hänet sen vuoksi kiireesti, että saisitte iloita nähdessänne hänet jälleen ja minullakin olisi vähemmän murheita.',
  },
  {
    chapter: 2,
    number: 29,
    baseText: 'Ottakaa siis hänet Herrassa iloiten vastaan ja kunnioittakaa hänen kaltaisiaan.',
    approvedText: 'Ottakaa siis hänet Herrassa iloiten vastaan ja kunnioittakaa hänen kaltaisiaan.',
    text: 'Ottakaa siis hänet iloiten vastaan Herran palvelijana ja kunnioittakaa hänen kaltaisiaan.',
  },
  {
    chapter: 2,
    number: 30,
    baseText: 'Sillä Kristuksen työn tähden hän joutui kuoleman partaalle, kun pani henkensä alttiiksi tehdäkseen minulle sen palveluksen, jota te ette voineet tehdä.',
    approvedText: 'Sillä Kristuksen työn tähden hän joutui kuoleman partaalle, kun pani henkensä alttiiksi tehdäkseen minulle sen palveluksen, jota te ette voineet tehdä.',
    text: 'Sillä Kristuksen työn tähden hän joutui kuoleman partaalle, kun pani henkensä alttiiksi tehdäkseen minulle sen palveluksen, jota te ette voineet tehdä.',
  },
  {
    chapter: 3,
    number: 1,
    baseText: 'Sitten vielä, veljeni, iloitkaa Herrassa! Minua ei kyllästytä kirjoittaa teille samoista asioista, ja teille se on turvaksi.',
    approvedText: 'Sitten vielä, veljeni, iloitkaa Herrassa! Minua ei kyllästytä kirjoittaa teille samoista asioista, ja teille se on turvaksi.',
    text: 'Sitten vielä, veljeni, iloitkaa Herrassa! Minua ei kyllästytä kirjoittaa teille samoista asioista, ja teille se on turvaksi.',
    sectionHeader: 'Tärkeintä on tuntea Kristus',
  },
  {
    chapter: 3,
    number: 2,
    baseText: 'Varokaa noita koiria, noita pahoja työntekijöitä, varokaa noita pilalle leikattuja!',
    approvedText: 'Varokaa noita koiria, noita pahoja työntekijöitä, varokaa noita pilalle leikattuja!',
    text: 'Varokaa noita koiria, noita pahoja työntekijöitä, varokaa noita pilalle leikattuja!',
  },
  {
    chapter: 3,
    number: 3,
    baseText: 'Todellisia ympärileikattuja olemme me, jotka Jumalan Hengessä palvelemme Jumalaa ja kerskaamme Kristuksessa Jeesuksessa emmekä luota lihaan,',
    approvedText: 'Todellisia ympärileikattuja olemme me, jotka Jumalan Hengessä palvelemme Jumalaa ja kerskaamme Kristuksessa Jeesuksessa emmekä luota lihaan,',
    text: 'Todellisia ympärileikattuja olemme me, jotka Jumalan Hengessä palvelemme Jumalaa ja kerskaamme Kristuksessa Jeesuksessa emmekä luota lihaan,',
  },
  {
    chapter: 3,
    number: 4,
    baseText: 'vaikka minulla on mihin luottaa lihassakin. Jos joku muu luulee voivansa luottaa lihaan, niin vielä enemmän minä.',
    approvedText: 'vaikka minulla on mihin luottaa lihassakin. Jos joku muu luulee voivansa luottaa lihaan, niin vielä enemmän minä.',
    text: 'vaikka minulla on mihin luottaa lihassakin. Jos joku muu luulee voivansa luottaa lihaan, niin vielä enemmän minä.',
  },
  {
    chapter: 3,
    number: 5,
    baseText: 'Minut on ympärileikattu kahdeksanpäiväisenä, olen Israelin kansaa, Benjaminin heimoa, heprealainen heprealaisista syntynyt, lakiin nähden fariseus,',
    approvedText: 'Minut on ympärileikattu kahdeksanpäiväisenä, olen Israelin kansaa, Benjaminin heimoa, heprealainen heprealaisista syntynyt, lakiin nähden fariseus,',
    text: 'Minut on ympärileikattu kahdeksanpäiväisenä, olen Israelin kansaa, Benjaminin heimoa, heprealainen heprealaisista syntynyt, lakiin nähden fariseus,',
  },
  {
    chapter: 3,
    number: 6,
    baseText: 'intoon nähden seurakunnan vainooja, lain vanhurskauteen nähden nuhteeton.',
    approvedText: 'intoon nähden seurakunnan vainooja, lain vanhurskauteen nähden nuhteeton.',
    text: 'intoon nähden seurakunnan vainooja, lain vanhurskauteen nähden nuhteeton.',
  },
  {
    chapter: 3,
    number: 7,
    baseText: 'Mutta mikä minulle oli voitto, sen olen Kristuksen tähden lukenut tappioksi.',
    approvedText: 'Mutta mikä minulle oli voitto, sen olen Kristuksen tähden lukenut tappioksi.',
    text: 'Mutta mikä minulle oli voitto, sen olen Kristuksen tähden lukenut tappioksi.',
  },
  {
    chapter: 3,
    number: 8,
    baseText: 'Niinpä minä luen kaiken tappioksi tuon ylen kalliin, Kristuksen Jeesuksen, minun Herrani, tuntemisen rinnalla. Hänen tähtensä olen menettänyt kaiken ja pidän sen roskana, että voittaisin omakseni Kristuksen',
    approvedText: 'Niinpä minä luen kaiken tappioksi tuon ylen kalliin, Kristuksen Jeesuksen, minun Herrani, tuntemisen rinnalla. Hänen tähtensä olen menettänyt kaiken ja pidän sen roskana, että voittaisin omakseni Kristuksen',
    text: 'Niinpä minä luen kaiken tappioksi tuon ylen kalliin, Kristuksen Jeesuksen, minun Herrani, tuntemisen rinnalla. Hänen tähtensä olen menettänyt kaiken ja pidän sen roskana, että voittaisin omakseni Kristuksen',
  },
  {
    chapter: 3,
    number: 9,
    baseText: 'ja minun havaittaisiin olevan hänessä ja omistavan, ei omaa vanhurskautta, joka tulee laista, vaan sen, joka tulee uskosta Kristukseen*, sen vanhurskauden, joka tulee Jumalasta uskon perusteella.',
    approvedText: 'ja minun havaittaisiin olevan hänessä ja omistavan, ei omaa vanhurskautta, joka tulee laista, vaan sen, joka tulee uskosta Kristukseen*, sen vanhurskauden, joka tulee Jumalasta uskon perusteella.',
    text: 'ja minun havaittaisiin olevan hänessä ja omistavan, ei omaa vanhurskautta, joka tulee laista, vaan sen, joka tulee uskosta Kristukseen*, sen vanhurskauden, joka tulee Jumalasta uskon perusteella.',
    footnotes: [{ marker: '3:9', text: '3:9 Tai ”Kristuksen uskosta”.', baseText: '3:9 Tai ”Kristuksen uskosta”.' }],
  },
  {
    chapter: 3,
    number: 10,
    baseText: 'Haluan tuntea Kristuksen ja hänen ylösnousemuksensa voiman ja hänen kärsimystensä osallisuuden ja tulla hänen kaltaisekseen samastumalla hänen kuolemaansa,',
    approvedText: 'Haluan tuntea Kristuksen ja hänen ylösnousemuksensa voiman ja hänen kärsimystensä osallisuuden ja tulla hänen kaltaisekseen samastumalla hänen kuolemaansa,',
    text: 'Haluan tuntea Kristuksen ja hänen ylösnousemuksensa voiman ja hänen kärsimystensä osallisuuden ja tulla hänen kaltaisekseen samastumalla hänen kuolemaansa,',
  },
  {
    chapter: 3,
    number: 11,
    baseText: 'kunhan vain pääsen ylösnousemukseen kuolleista.\nKohti päämäärää!',
    approvedText: 'kunhan vain pääsen ylösnousemukseen kuolleista.\nKohti päämäärää!',
    text: 'kunhan vain pääsen ylösnousemukseen kuolleista.\nKohti päämäärää!',
  },
  {
    chapter: 3,
    number: 12,
    baseText: 'Ei niin, että olisin jo saavuttanut sen tai tullut täydelliseksi, vaan minä riennän sitä kohti, että voittaisin sen omakseni, koskapa Kristus Jeesus on voittanut minut omakseen.',
    approvedText: 'Ei niin, että olisin jo saavuttanut sen tai tullut täydelliseksi, vaan minä riennän sitä kohti, että voittaisin sen omakseni, koskapa Kristus Jeesus on voittanut minut omakseen.',
    text: 'En tarkoita, että olisin jo saavuttanut päämääräni tai tullut täydelliseksi, vaan minä riennän sitä kohti, että voittaisin sen omakseni, koskapa Kristus Jeesus on voittanut minut omakseen.',
  },
  {
    chapter: 3,
    number: 13,
    baseText: 'Veljet, minä en katso sitä vielä saavuttaneeni. Yhden minä kuitenkin teen: unohtaen sen, mikä on takana, ja kurottautuen sitä kohti, mikä on edessä,',
    approvedText: 'Veljet, minä en katso sitä vielä saavuttaneeni. Yhden minä kuitenkin teen: unohtaen sen, mikä on takana, ja kurottautuen sitä kohti, mikä on edessä,',
    text: 'Veljet, minä en katso sitä vielä saavuttaneeni. Yhden minä kuitenkin teen: unohtaen sen, mikä on takana, ja kurottautuen sitä kohti, mikä on edessä,',
  },
  {
    chapter: 3,
    number: 14,
    baseText: 'minä riennän kohti päämäärää saadakseni voittopalkinnon, jonka omistamiseen Jumala on minut kutsunut taivaallisella kutsulla Kristuksessa Jeesuksessa.',
    approvedText: 'minä riennän kohti päämäärää saadakseni voittopalkinnon, jonka omistamiseen Jumala on minut kutsunut taivaallisella kutsulla Kristuksessa Jeesuksessa.',
    text: 'minä riennän kohti päämäärää saadakseni voittopalkinnon, jonka omistamiseen Jumala on minut kutsunut taivaallisella kutsulla Kristuksessa Jeesuksessa.',
  },
  {
    chapter: 3,
    number: 15,
    baseText: 'Ajatelkaamme siis näin, niin monta kuin meitä on täydellistä. Jos jossakin kohden ajattelette toisin, Jumala kyllä ilmoittaa teille, kuinka asia on.',
    approvedText: 'Ajatelkaamme siis näin, niin monta kuin meitä on täydellistä. Jos jossakin kohden ajattelette toisin, Jumala kyllä ilmoittaa teille, kuinka asia on.',
    text: 'Ajatelkaamme siis näin, niin monta kuin meitä on täydellistä. Jos jossakin kohden ajattelette toisin, Jumala kyllä ilmoittaa teille, kuinka asia on.',
  },
  {
    chapter: 3,
    number: 16,
    baseText: 'Kunhan vain, mihin saakka olemme ehtineetkin, vaellamme samaa tietä*!',
    approvedText: 'Kunhan vain, mihin saakka olemme ehtineetkin, vaellamme samaa tietä*!',
    text: 'Kunhan vain, mihin saakka olemme ehtineetkin, vaellamme samaa tietä*!',
    footnotes: [{ marker: '3:16', text: '3:16 Bysanttilaisessa tekstissä ”saman säännön mukaan”. (tarpeen?)', baseText: '3:16 Bysanttilaisessa tekstissä ”saman säännön mukaan”. (tarpeen?)' }],
  },
  {
    chapter: 3,
    number: 17,
    baseText: 'Olkaa minun seuraajiani, veljet, ja tarkatkaa niitä, jotka vaeltavat sen esikuvan mukaan, jonka me olemme teille antaneet.',
    approvedText: 'Olkaa minun seuraajiani, veljet, ja tarkatkaa niitä, jotka vaeltavat sen esikuvan mukaan, jonka me olemme teille antaneet.',
    text: 'Olkaa minun seuraajiani, veljet, ja tarkatkaa niitä, jotka vaeltavat sen esikuvan mukaan, jonka me olemme teille antaneet.',
  },
  {
    chapter: 3,
    number: 18,
    baseText: 'Sillä monet, joista olen usein teille sanonut ja nyt aivan itkien sanon, vaeltavat Kristuksen ristin vihollisina.',
    approvedText: 'Sillä monet, joista olen usein teille sanonut ja nyt aivan itkien sanon, vaeltavat Kristuksen ristin vihollisina.',
    text: 'Sillä monet, joista olen usein teille sanonut ja nyt aivan itkien sanon, vaeltavat Kristuksen ristin vihollisina.',
  },
  {
    chapter: 3,
    number: 19,
    baseText: 'Heidän loppunsa on kadotus. Vatsa on heidän jumalansa ja häpeä heidän kunniansa, ja maallisiin on heidän mielensä.',
    approvedText: 'Heidän loppunsa on kadotus. Vatsa on heidän jumalansa ja häpeä heidän kunniansa, ja maallisiin on heidän mielensä.',
    text: 'Heidän loppunsa on kadotus. Vatsa on heidän jumalansa ja häpeä heidän kunniansa, ja maallisiin on heidän mielensä.',
  },
  {
    chapter: 3,
    number: 20,
    baseText: 'Mutta meidän yhteiskuntamme on taivaissa, ja sieltä me myös odotamme Herraa Jeesusta Kristusta Vapahtajaksi.',
    approvedText: 'Mutta meidän yhteiskuntamme on taivaissa, ja sieltä me myös odotamme Herraa Jeesusta Kristusta Vapahtajaksi.',
    text: 'Mutta meidän yhteiskuntamme on taivaissa, ja sieltä me myös odotamme pelastajaksi Herraa Jeesusta Kristusta.',
  },
  {
    chapter: 3,
    number: 21,
    baseText: 'Hän muuttaa meidän alennustilassa olevan ruumiimme kirkkautensa ruumiin kaltaiseksi sillä voimallaan, jolla hän myös kykenee alistamaan kaiken valtaansa.',
    approvedText: 'Hän muuttaa meidän alennustilassa olevan ruumiimme kirkkautensa ruumiin kaltaiseksi sillä voimallaan, jolla hän myös kykenee alistamaan kaiken valtaansa.',
    text: 'Hän muuttaa meidän alennustilassa olevan ruumiimme kirkkautensa ruumiin kaltaiseksi sillä voimallaan, jolla hän myös kykenee alistamaan kaiken valtaansa.',
  },
  {
    chapter: 4,
    number: 1,
    baseText: 'Rakkaat ja ikävöidyt veljeni, te minun iloni ja kruununi, seisokaa/seiskää siis lujina Herrassa, rakkaat!',
    approvedText: 'Rakkaat ja ikävöidyt veljeni, te minun iloni ja kruununi, seisokaa/seiskää siis lujina Herrassa, rakkaat!',
    text: 'Rakkaat ja ikävöidyt veljeni, te minun iloni ja kruununi, seisokaa/seiskää siis lujina Herrassa, rakkaat!',
    sectionHeader: 'Kehotuksia seurakunnalle',
  },
  {
    chapter: 4,
    number: 2,
    baseText: 'Euodiaa ja Syntykeä kehotan olemaan yksimielisiä Herrassa.',
    approvedText: 'Euodiaa ja Syntykeä kehotan olemaan yksimielisiä Herrassa.',
    text: 'Euodiaa ja Syntykeä kehotan olemaan yksimielisiä Herrassa.',
  },
  {
    chapter: 4,
    number: 3,
    baseText: 'Pyydän myös sinua, sinä todellinen työtoveri*, auttamaan näitä naisia, sillä he ovat taistelleet evankeliumin hyväksi yhdessä minun sekä Clemensin ja muiden työtoverieni kanssa, joiden nimet ovat elämän kirjassa.',
    approvedText: 'Pyydän myös sinua, sinä todellinen työtoveri*, auttamaan näitä naisia, sillä he ovat taistelleet evankeliumin hyväksi yhdessä minun sekä Clemensin ja muiden työtoverieni kanssa, joiden nimet ovat elämän kirjassa.',
    text: 'Pyydän myös sinua, sinä todellinen työtoveri*, auttamaan näitä naisia, sillä he ovat taistelleet evankeliumin hyväksi yhdessä minun sekä Clemensin ja muiden työtoverieni kanssa, joiden nimet ovat elämän kirjassa.',
    footnotes: [{ marker: '4:3', text: '4:3 Kreik. syzygos merkitsee ’aisapari’; voi olla myös erisnimi.', baseText: '4:3 Kreik. syzygos merkitsee ’aisapari’; voi olla myös erisnimi.' }, { marker: '4:3', text: '4:3 Kreik. syzygos merkitsee ’aisapari’.', baseText: '4:3 Kreik. syzygos merkitsee ’aisapari’.' }, { marker: '4:3', text: '4:3 Kirjaimellisesti ”aisapari”.', baseText: '4:3 Kirjaimellisesti ”aisapari”.' }],
  },
  {
    chapter: 4,
    number: 4,
    baseText: 'Iloitkaa aina Herrassa! Vieläkin minä sanon: iloitkaa!',
    approvedText: 'Iloitkaa aina Herrassa! Vieläkin minä sanon: iloitkaa!',
    text: 'Iloitkaa aina Herrassa! Vieläkin minä sanon: iloitkaa!',
  },
  {
    chapter: 4,
    number: 5,
    baseText: 'Tulkoon teidän lempeytenne kaikkien ihmisten tietoon. Herra on lähellä.',
    approvedText: 'Tulkoon teidän lempeytenne kaikkien ihmisten tietoon. Herra on lähellä.',
    text: 'Tulkoon teidän lempeytenne kaikkien ihmisten tietoon. Herra on lähellä.',
  },
  {
    chapter: 4,
    number: 6,
    baseText: 'Älkää olko mistään huolissanne, vaan kaikessa saattakaa pyyntönne rukoillen ja anoen kiitoksen kanssa Jumalan tietoon,',
    approvedText: 'Älkää olko mistään huolissanne, vaan kaikessa saattakaa pyyntönne rukoillen ja anoen kiitoksen kanssa Jumalan tietoon,',
    text: 'Älkää olko mistään huolissanne, vaan kaikessa saattakaa pyyntönne rukoillen ja anoen kiitoksen kanssa Jumalan tietoon,',
  },
  {
    chapter: 4,
    number: 7,
    baseText: 'ja Jumalan rauha, joka on kaikkea ymmärrystä ylempi, varjelee teidän sydämenne ja ajatuksenne Kristuksessa Jeesuksessa.',
    approvedText: 'ja Jumalan rauha, joka on kaikkea ymmärrystä ylempi, varjelee teidän sydämenne ja ajatuksenne Kristuksessa Jeesuksessa.',
    text: 'ja Jumalan rauha, joka on kaikkea ymmärrystä ylempi, varjelee teidän sydämenne ja ajatuksenne Kristuksessa Jeesuksessa.',
  },
  {
    chapter: 4,
    number: 8,
    baseText: 'Sitten vielä, veljet, kaikki mikä on totta, mikä kunnioitettavaa ja oikeaa, mikä puhdasta, rakastettavaa ja hyvältä kuulostavaa, jos on jokin hyve ja jotakin kiitettävää, sitä ajatelkaa.',
    approvedText: 'Sitten vielä, veljet, kaikki mikä on totta, mikä kunnioitettavaa ja oikeaa, mikä puhdasta, rakastettavaa ja hyvältä kuulostavaa, jos on jokin hyve ja jotakin kiitettävää, sitä ajatelkaa.',
    text: 'Sitten vielä, veljet, kaikki mikä on totta, mikä kunnioitettavaa ja oikeaa, mikä puhdasta, rakastettavaa ja hyvältä kuulostavaa, jos on jokin hyve ja jotakin kiitettävää, sitä ajatelkaa.',
  },
  {
    chapter: 4,
    number: 9,
    baseText: 'Mitä myös olette minulta oppineet ja saaneet, mitä minulta kuulleet ja minusta nähneet, sitä tehkää, niin rauhan Jumala on oleva teidän kanssanne.',
    approvedText: 'Mitä myös olette minulta oppineet ja saaneet, mitä minulta kuulleet ja minusta nähneet, sitä tehkää, niin rauhan Jumala on oleva teidän kanssanne.',
    text: 'Mitä myös olette minulta oppineet ja saaneet, mitä minulta kuulleet ja minusta nähneet, sitä tehkää, niin rauhan Jumala on oleva teidän kanssanne.',
  },
  {
    chapter: 4,
    number: 10,
    baseText: 'Ilahduin suuresti Herrassa, että te vihdoinkin havahduitte huolehtimaan minusta. Siihen teillä on toki ollut halua mutta ei tilaisuutta.',
    approvedText: 'Ilahduin suuresti Herrassa, että te vihdoinkin havahduitte huolehtimaan minusta. Siihen teillä on toki ollut halua mutta ei tilaisuutta.',
    text: 'Ilahduin suuresti Herrassa, että te vihdoinkin havahduitte huolehtimaan minusta. Siihen teillä on toki ollut halua mutta ei tilaisuutta.',
    sectionHeader: 'Kiitokset filippiläisille',
  },
  {
    chapter: 4,
    number: 11,
    baseText: 'En sano tätä puutteen vuoksi, sillä olen oppinut tyytymään oloihini.',
    approvedText: 'En sano tätä puutteen vuoksi, sillä olen oppinut tyytymään oloihini.',
    text: 'En sano tätä puutteen vuoksi, sillä olen oppinut tyytymään oloihini.',
  },
  {
    chapter: 4,
    number: 12,
    baseText: 'Osaan elää niukkuudessa, osaan myös elää runsaudessa. Olen tottunut kaikkeen ja kaikenlaisiin oloihin, olemaan kylläinen ja nälkäinen, elämään runsaudessa ja puutteessa.',
    approvedText: 'Osaan elää niukkuudessa, osaan myös elää runsaudessa. Olen tottunut kaikkeen ja kaikenlaisiin oloihin, olemaan kylläinen ja nälkäinen, elämään runsaudessa ja puutteessa.',
    text: 'Osaan elää niukkuudessa, osaan myös elää runsaudessa. Olen tottunut kaikkeen ja kaikenlaisiin oloihin, olemaan kylläinen ja nälkäinen, elämään runsaudessa ja puutteessa.',
  },
  {
    chapter: 4,
    number: 13,
    baseText: 'Kaiken minä voin hänessä, joka minua vahvistaa.',
    approvedText: 'Kaiken minä voin hänessä, joka minua vahvistaa.',
    text: 'Kaiken minä voin hänessä, joka minua vahvistaa.',
  },
  {
    chapter: 4,
    number: 14,
    baseText: 'Teitte kuitenkin hyvin, kun otitte osaa minun ahdinkooni.',
    approvedText: 'Teitte kuitenkin hyvin, kun otitte osaa minun ahdinkooni.',
    text: 'Teitte kuitenkin hyvin, kun otitte osaa minun ahdinkooni.',
  },
  {
    chapter: 4,
    number: 15,
    baseText: 'Tiedättehän te filippiläiset itsekin, että evankeliumin alkuaikoina, kun lähdin Makedoniasta, ei mikään muu seurakunta kuin te yksin ryhtynyt kanssani tiliyhteyteen annetusta ja saadusta.',
    approvedText: 'Tiedättehän te filippiläiset itsekin, että evankeliumin alkuaikoina, kun lähdin Makedoniasta, ei mikään muu seurakunta kuin te yksin ryhtynyt kanssani tiliyhteyteen annetusta ja saadusta.',
    text: 'Tiedättehän te filippiläiset itsekin, että evankeliumin alkuaikoina, kun lähdin Makedoniasta, ei mikään muu seurakunta kuin te yksin ryhtynyt kanssani tiliyhteyteen annetusta ja saadusta.',
  },
  {
    chapter: 4,
    number: 16,
    baseText: 'Tessalonikaankin te lähetitte minulle kerran, jopa kahdesti, mitä tarvitsin.',
    approvedText: 'Tessalonikaankin te lähetitte minulle kerran, jopa kahdesti, mitä tarvitsin.',
    text: 'Tessalonikaankin te lähetitte minulle kerran, jopa kahdesti, mitä tarvitsin.',
  },
  {
    chapter: 4,
    number: 17,
    baseText: 'En toki tavoittele lahjoja vaan haluan, että teidän hyväksenne karttuu hedelmää.',
    approvedText: 'En toki tavoittele lahjoja vaan haluan, että teidän hyväksenne karttuu hedelmää.',
    text: 'En toki tavoittele lahjoja vaan haluan, että teidän hyväksenne karttuu hedelmää.',
  },
  {
    chapter: 4,
    number: 18,
    baseText: 'Olen saanut kaikkea, jopa runsaasti. Minulla on kaikkea yllin kyllin saatuani Epafroditokselta teidän lähetyksenne, joka on suloinen tuoksu, kelvollinen, Jumalan mielen mukainen uhri.',
    approvedText: 'Olen saanut kaikkea, jopa runsaasti. Minulla on kaikkea yllin kyllin saatuani Epafroditokselta teidän lähetyksenne, joka on suloinen tuoksu, kelvollinen, Jumalan mielen mukainen uhri.',
    text: 'Olen saanut kaikkea, jopa runsaasti. Minulla on kaikkea yllin kyllin saatuani Epafroditokselta teidän lähetyksenne, joka on suloinen tuoksu, kelvollinen, Jumalan mielen mukainen uhri.',
  },
  {
    chapter: 4,
    number: 19,
    baseText: 'Minun Jumalani on täyttävä/täyttää kaikki teidän tarpeenne kirkkaudessa olevan rikkautensa mukaan Kristuksessa Jeesuksessa.',
    approvedText: 'Minun Jumalani on täyttävä/täyttää kaikki teidän tarpeenne kirkkaudessa olevan rikkautensa mukaan Kristuksessa Jeesuksessa.',
    text: 'Minun Jumalani on täyttävä/täyttää kaikki teidän tarpeenne kirkkaudessa olevan rikkautensa mukaan Kristuksessa Jeesuksessa.',
  },
  {
    chapter: 4,
    number: 20,
    baseText: 'Jumalalle ja meidän Isällemme kunnia, aina ja iankaikkisesti! Aamen.',
    approvedText: 'Jumalalle ja meidän Isällemme kunnia, aina ja iankaikkisesti! Aamen.',
    text: 'Jumalalle ja meidän Isällemme kunnia, aina ja iankaikkisesti! Aamen.',
  },
  {
    chapter: 4,
    number: 21,
    baseText: 'Tervehtikää kaikkia pyhiä Kristuksessa Jeesuksessa. Luonani olevat veljet lähettävät teille terveisiä.',
    approvedText: 'Tervehtikää kaikkia pyhiä Kristuksessa Jeesuksessa. Luonani olevat veljet lähettävät teille terveisiä.',
    text: 'Tervehtikää kaikkia pyhiä Kristuksessa Jeesuksessa / (92) Jeesuksen Kristuksen pyhiä. Veljet, jotka ovat luonani, lähettävät teille terveisiä.',
    sectionHeader: 'Lopputervehdys',
  },
  {
    chapter: 4,
    number: 22,
    baseText: 'Kaikki pyhät tervehtivät teitä, varsinkin ne, jotka ovat keisarin huonetta*/palveluskuntaa.',
    approvedText: 'Kaikki pyhät tervehtivät teitä, varsinkin ne, jotka ovat keisarin huonetta*/palveluskuntaa.',
    text: 'Kaikki pyhät tervehtivät teitä, varsinkin ne, jotka ovat keisarin huonetta*/palveluskuntaa.',
    footnotes: [{ marker: '4:22', text: '4:22 Saattoivat olla keisarillisen suvun jäseniä tai keisarin palatsin palveluskuntaa.', baseText: '4:22 Saattoivat olla keisarillisen suvun jäseniä tai keisarin palatsin palveluskuntaa.' }],
  },
  {
    chapter: 4,
    number: 23,
    baseText: 'Herran Jeesuksen Kristuksen armo olkoon teidän henkenne kanssa.',
    approvedText: 'Herran Jeesuksen Kristuksen armo olkoon teidän henkenne kanssa.',
    text: 'Herran Jeesuksen Kristuksen armo olkoon teidän henkenne kanssa.',
  },
]


export const SEED_USERS: User[] = [
  // Dual-role members (tekstiryhmä + hallitus)
  { id: 'leino-kimmo', name: 'Kimmo Leino', roles: ['tekstiryhma', 'hallitus'], roleLabel: '1. varapj.' },
  { id: 'ahvenainen-martti', name: 'Martti Ahvenainen', roles: ['tekstiryhma', 'hallitus'], roleLabel: '' },
  { id: 'kivinen-riku', name: 'Riku Kivinen', roles: ['tekstiryhma', 'hallitus'], roleLabel: '2. varapj.' },
  // Tekstiryhmä only
  { id: 'peltola-kimmo', name: 'Kimmo Peltola', roles: ['tekstiryhma'], roleLabel: '' },
  // Seurantaryhmä
  { id: 'seurantaryhma-a', name: 'Seurantaryhmän jäsen A', roles: ['seurantaryhma'], roleLabel: '' },
  { id: 'seurantaryhma-b', name: 'Seurantaryhmän jäsen B', roles: ['seurantaryhma'], roleLabel: '' },
  // Hallitus only
  { id: 'liukko-arto', name: 'Arto Liukko', roles: ['hallitus'], roleLabel: 'pj.' },
  { id: 'kaikkonen-sointu', name: 'Sointu Kaikkonen', roles: ['hallitus'], roleLabel: '' },
  { id: 'mantsinen-matti', name: 'Matti Mantsinen', roles: ['hallitus'], roleLabel: '' },
  { id: 'valimaki-maria', name: 'Maria Välimäki', roles: ['hallitus'], roleLabel: 'sihteeri' },
]

export const SEED_TEXT_WORKS: TextWork[] = [
  {
    id: 'tw-1',
    scope: { book: 'Phil' },
    status: 'luonnos',
    statusChangedAt: '2026-04-16T09:00:00Z',
    publishedForFeedbackAt: '2026-04-12T10:00:00Z',
  },
  {
    id: 'tw-2',
    scope: { book: 'Col' },
    status: 'julkaistu_palautteelle',
    statusChangedAt: '2026-04-18T10:00:00Z',
    publishedForFeedbackAt: '2026-04-18T10:00:00Z',
  },
  {
    id: 'tw-3',
    scope: { book: 'Gal' },
    status: 'lahetetty_hallitukselle',
    statusChangedAt: '2026-04-22T14:00:00Z',
    publishedForFeedbackAt: '2026-04-15T09:00:00Z',
    submittedToHallitusAt: '2026-04-22T14:00:00Z',
    submissionProposalId: 'proposal-tw3',
  },
  {
    id: 'tw-4',
    scope: { book: '1Thess' },
    status: 'hyvaksytty',
    statusChangedAt: '2026-04-25T16:00:00Z',
    publishedForFeedbackAt: '2026-04-10T09:00:00Z',
    submittedToHallitusAt: '2026-04-20T12:00:00Z',
    submissionProposalId: 'proposal-tw4',
  },
]

const ALL_VOTERS = ['liukko-arto', 'kaikkonen-sointu', 'mantsinen-matti', 'valimaki-maria', 'ahvenainen-martti', 'kivinen-riku', 'leino-kimmo']

export const SEED_PROPOSALS: Proposal[] = [
  // tw-3 (Gal): partial votes — Arto approved, 6 pending
  {
    id: 'proposal-tw3',
    textWorkId: 'tw-3',
    snapshotId: 'snapshot-tw3-submission',
    selectedVoters: ALL_VOTERS,
    selectedVerses: [1, 2, 3, 4, 5, 6, 7],
    rationale: 'Galatalaiskirjeen luku 1 jakeet 1–7 on käännetty uudelleen. Keskeisimmät muutokset: jae 1 selvennetty apostoliuden alkuperää ja jae 4 "maailmanaika"-termi modernisoitu. Seurantaryhmä on antanut palautteen ja muutokset on käsitelty.',
    votes: [
      { userId: 'liukko-arto', decision: 'approve', createdAt: '2026-04-24T10:00:00Z' },
    ],
    createdAt: '2026-04-22T14:00:00Z',
  },
  // tw-4 (1 Tess): all approved — resolved proposal
  {
    id: 'proposal-tw4',
    textWorkId: 'tw-4',
    snapshotId: 'snapshot-tw4-submission',
    selectedVoters: ALL_VOTERS,
    selectedVerses: [1, 2, 3, 4, 5],
    rationale: '1. Tessalonikalaiskirjeen alkutervehdys (jakeet 1–5) on päivitetty. Muutokset koskevat lähinnä sanajärjestystä ja vanhahtavien ilmausten modernisointia. Seurantaryhmän palaute huomioitu ja kaikki avoimet kommentit käsitelty.',
    votes: [
      { userId: 'liukko-arto', decision: 'approve', createdAt: '2026-04-24T14:00:00Z' },
      { userId: 'kaikkonen-sointu', decision: 'approve', createdAt: '2026-04-24T15:00:00Z' },
      { userId: 'mantsinen-matti', decision: 'approve', createdAt: '2026-04-24T16:00:00Z' },
      { userId: 'valimaki-maria', decision: 'approve', createdAt: '2026-04-25T09:00:00Z' },
      { userId: 'ahvenainen-martti', decision: 'approve', createdAt: '2026-04-25T10:00:00Z' },
      { userId: 'kivinen-riku', decision: 'approve', createdAt: '2026-04-25T14:00:00Z' },
      { userId: 'leino-kimmo', decision: 'approve', createdAt: '2026-04-25T16:00:00Z' },
    ],
    createdAt: '2026-04-20T12:00:00Z',
    resolvedAt: '2026-04-25T16:00:00Z',
  },
]

export const SEED_COMMENTS: Comment[] = [
  // tw-2: seurantaryhmä comments on chapter 3
  {
    id: 'comment-s1',
    textWorkId: 'tw-2',
    verseAnchor: { chapter: 4, verseStart: 1 },
    verseSnapshot: 'Fil. 3:1 teksti.',
    authorId: 'seurantaryhma-a',
    text: 'Aloituksen sanajärjestys voisi olla luontevampi.',
    thread: 'seurantaryhma',
    status: 'avoin',
    createdAt: '2026-04-19T09:00:00Z',
  },
  {
    id: 'comment-s2',
    textWorkId: 'tw-2',
    verseAnchor: { chapter: 4, verseStart: 3 },
    verseSnapshot: 'Fil. 3:3 teksti.',
    authorId: 'seurantaryhma-b',
    text: 'Kreikan sanan vivahde ei välity tässä muotoilussa.',
    thread: 'seurantaryhma',
    status: 'avoin',
    createdAt: '2026-04-19T14:00:00Z',
  },
  {
    id: 'comment-s3',
    textWorkId: 'tw-2',
    verseAnchor: { chapter: 4, verseStart: 5 },
    verseSnapshot: 'Fil. 3:5 teksti.',
    authorId: 'seurantaryhma-a',
    text: 'Hyvä muotoilu, ei huomautettavaa.',
    thread: 'seurantaryhma',
    status: 'kasitelty',
    resolvedBy: 'leino-kimmo',
    resolvedAt: '2026-04-20T08:00:00Z',
    createdAt: '2026-04-19T15:00:00Z',
  },
  // tw-3 (Gal): comments for hallitus review demo
  {
    id: 'comment-g1',
    textWorkId: 'tw-3',
    verseAnchor: { chapter: 1, verseStart: 1 },
    verseSnapshot: 'ei ihmisten valitsema eikä ihmisen lähettämä',
    authorId: 'peltola-kimmo',
    text: '"Ei ihmisten valitsema" — kreikassa painotus on negaatiossa, käännös voisi olla napakampi.',
    thread: 'tekstiryhma',
    status: 'avoin',
    createdAt: '2026-04-21T10:00:00Z',
  },
  {
    id: 'comment-g2',
    textWorkId: 'tw-3',
    verseAnchor: { chapter: 1, verseStart: 4 },
    verseSnapshot: 'nykyisestä pahasta maailmanajasta',
    authorId: 'seurantaryhma-a',
    text: '"Maailmanaika" on epätavallinen sana — olisiko "aikakausi" selkeämpi lukijalle?',
    thread: 'seurantaryhma',
    status: 'avoin',
    createdAt: '2026-04-21T14:00:00Z',
  },
  // tw-1: tekstiryhma comments on chapter 4
  {
    id: 'comment-t1',
    textWorkId: 'tw-1',
    verseAnchor: { chapter: 4, verseStart: 7 },
    verseSnapshot: 'ja Jumalan rauha, joka ylittää kaiken ymmärryksen, varjelee teidän sydämenne ja ajatuksenne Kristuksessa Jeesuksessa.',
    authorId: 'peltola-kimmo',
    text: '"Ylittää kaiken ymmärryksen" \u2014 onko tämä parempi kuin "on kaikkea ymmärrystä ylempi"? Molemmat toimivat.',
    thread: 'tekstiryhma',
    status: 'avoin',
    createdAt: '2026-04-17T11:00:00Z',
  },
  {
    id: 'comment-t2',
    textWorkId: 'tw-1',
    verseAnchor: { chapter: 4, verseStart: 11 },
    verseSnapshot: 'En sano tätä puutteen vuoksi, sillä olen oppinut tulemaan toimeen kulloisessakin tilanteessani.',
    authorId: 'leino-kimmo',
    text: '"Tulemaan toimeen kulloisessakin tilanteessani" on pitkä \u2014 "tyytymään oloihini" on tiiviimpi ja perinteisempi.',
    thread: 'tekstiryhma',
    status: 'avoin',
    createdAt: '2026-04-19T09:15:00Z',
  },
]

export const SEED_MERKINNAT: Merkinta[] = [
  {
    id: 'merkinta-1',
    verses: [{ chapter: 4, verseNumber: 3, text: 'työtoveri' }],
    authorId: 'leino-kimmo',
    note: 'kr. syzygos \u2014 aisapari, voi olla myös erisnimi Syzygos',
    createdAt: '2026-04-16T08:00:00Z',
  },
  {
    id: 'merkinta-2',
    verses: [{ chapter: 4, verseNumber: 8, text: 'hyvältä kuulostavaa' }],
    authorId: 'leino-kimmo',
    note: 'kr. euph\u0113ma \u2014 hyvä maine, kiitettävä puhe; vrt. "arvostettavaa"',
    createdAt: '2026-04-16T08:30:00Z',
  },
  {
    id: 'merkinta-3',
    verses: [{ chapter: 4, verseNumber: 19, text: 'täyttävä' }],
    authorId: 'leino-kimmo',
    note: 'kr. pl\u0113rosei \u2014 fut. indikatiivimuoto, lupaus: "on täyttävä" vai "täyttää"',
    createdAt: '2026-04-17T10:30:00Z',
  },
  {
    id: 'merkinta-4',
    verses: [{ chapter: 4, verseNumber: 13, text: 'Kaiken minä voin' }],
    authorId: 'peltola-kimmo',
    note: 'Tunnetuin Filippiläiskirjeen jae \u2014 muotoilu on vakiintunut, ei syytä muuttaa',
    createdAt: '2026-04-18T16:00:00Z',
  },
]

// Reference translations for the comparison panel (v2.0)
export interface ReferenceTranslation {
  id: string
  label: string
  language: string
  verses: { chapter: number; number: number; text: string }[]
}

export const REFERENCE_TRANSLATIONS: ReferenceTranslation[] = [
  {
    id: 'rk1933',
    label: 'RK 1933/38',
    language: 'fi',
    verses: SEED_VERSES.map(v => ({ chapter: v.chapter, number: v.number, text: v.baseText })),
  },
]

function snapshotFromVerses(verses: Verse[]) {
  return {
    verseTexts: verses.map(v => ({ chapter: v.chapter, number: v.number, text: v.baseText })),
    footnoteTexts: verses.flatMap(v =>
      (v.footnotes ?? []).map(fn => ({ chapter: v.chapter, verse: v.number, marker: fn.marker, text: fn.baseText }))
    ),
    sectionHeaderTexts: verses
      .filter(v => v.sectionHeader)
      .map(v => ({ chapter: v.chapter, verse: v.number, text: v.sectionHeader! })),
  }
}

export const SEED_SNAPSHOTS: Snapshot[] = [
  // Base version — all Philippians
  {
    id: 'snapshot-tw1-publication',
    textWorkId: 'tw-1',
    type: 'publication',
    name: 'Pohjaversio (RK12)',
    createdAt: '2026-04-12T10:00:00Z',
    createdBy: 'leino-kimmo',
    ...snapshotFromVerses(SEED_VERSES),
  },
  // Internal snapshot — first draft round
  {
    id: 'snapshot-tw1-internal',
    textWorkId: 'tw-1',
    type: 'internal',
    name: 'Ensimmäinen luonnoskierros',
    createdAt: '2026-04-14T17:00:00Z',
    createdBy: 'leino-kimmo',
    ...snapshotFromVerses(SEED_VERSES),
  },
  // Submission snapshot for tw-3
  {
    id: 'snapshot-tw3-submission',
    textWorkId: 'tw-3',
    type: 'submission',
    createdAt: '2026-04-22T14:00:00Z',
    createdBy: 'leino-kimmo',
    verseTexts: [
      { chapter: 1, number: 1, text: 'Paavali, apostoli — ei ihmisten valitsema eikä ihmisen lähettämä, vaan Jeesuksen Kristuksen ja Isän Jumalan, joka herätti hänet kuolleista —' },
      { chapter: 1, number: 2, text: 'ja kaikki kanssani olevat veljet, Galatian seurakunnille.' },
      { chapter: 1, number: 3, text: 'Armo teille ja rauha Jumalalta, meidän Isältämme, ja Herralta Jeesukselta Kristukselta,' },
      { chapter: 1, number: 4, text: 'joka antoi itsensä meidän syntiemme tähden, pelastaakseen meidät nykyisestä pahasta maailmanajasta meidän Jumalamme ja Isämme tahdon mukaan.' },
      { chapter: 1, number: 5, text: 'Hänelle kunnia aina ja iankaikkisesti. Aamen.' },
      { chapter: 1, number: 6, text: 'Minä ihmettelen, että te niin pian käännytte pois hänestä, joka on kutsunut teidät Kristuksen armosta, toisen evankeliumin puoleen,' },
      { chapter: 1, number: 7, text: 'vaikka mitään toista evankeliumia ei ole. On vain muutamia, jotka hämmentävät teitä ja tahtovat vääristää Kristuksen evankeliumin.' },
    ],
    footnoteTexts: [],
    sectionHeaderTexts: [],
  },
  // Submission snapshot for tw-4
  {
    id: 'snapshot-tw4-submission',
    textWorkId: 'tw-4',
    type: 'submission',
    createdAt: '2026-04-20T12:00:00Z',
    createdBy: 'peltola-kimmo',
    verseTexts: [
      { chapter: 1, number: 1, text: 'Paavali, Silvanus ja Timoteus Tessalonikan seurakunnalle, joka on Isässä Jumalassa ja Herrassa Jeesuksessa Kristuksessa. Armo teille ja rauha.' },
      { chapter: 1, number: 2, text: 'Me kiitämme Jumalaa aina teidän kaikkien tähden ja muistamme teitä rukouksissamme lakkaamatta.' },
      { chapter: 1, number: 3, text: 'Me muistamme Jumalamme ja Isämme edessä lakkaamatta teidän uskon työtänne, rakkautenne vaivannäköä ja toivonne kestävyyttä meidän Herrassamme Jeesuksessa Kristuksessa.' },
      { chapter: 1, number: 4, text: 'Me tiedämme, Jumalan rakkamat veljet, että teidät on valittu,' },
      { chapter: 1, number: 5, text: 'sillä meidän evankeliumimme ei tullut teidän luoksenne ainoastaan sanoin, vaan myös voimassa ja Pyhässä Hengessä ja täydessä varmuudessa — tiedättehän, millaisiksi me tulimme teidän keskuudessanne teidän tähtenne.' },
    ],
    footnoteTexts: [],
    sectionHeaderTexts: [],
  },
]

export const SEED_ACTIVITY: ActivityEntry[] = [
  {
    id: 'act-2',
    timestamp: '2026-04-25T16:00:00Z',
    userId: 'kaikkonen-sointu',
    textWorkId: 'tw-4',
    action: 'Hyväksytty',
    detail: 'Hallitus hyväksyi tekstin',
  },
  {
    id: 'act-3',
    timestamp: '2026-04-24T10:00:00Z',
    userId: 'liukko-arto',
    textWorkId: 'tw-3',
    action: 'Äänestetty',
    detail: 'Ääni annettu',
  },
  {
    id: 'act-4',
    timestamp: '2026-04-22T14:00:00Z',
    userId: 'leino-kimmo',
    textWorkId: 'tw-3',
    action: 'Lähetetty hallitukselle',
    detail: 'Teksti lähetetty hallituksen äänestettäväksi',
  },
  {
    id: 'act-5',
    timestamp: '2026-04-19T09:00:00Z',
    userId: 'seurantaryhma-a',
    textWorkId: 'tw-2',
    action: 'Uusi kommentti',
    detail: 'Kommentti lisätty',
  },
  {
    id: 'act-6',
    timestamp: '2026-04-18T10:00:00Z',
    userId: 'leino-kimmo',
    textWorkId: 'tw-2',
    action: 'Julkaistu palautteelle',
    detail: 'Teksti julkaistu seurantaryhmälle palautekierrokselle',
  },
]
